SecondHandBusinessPlatform/Controllers/DemandController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SecondHandBusinessPlatform.Controllers
{
    public class DemandController : Controller
    {
        //
        // GET: /Demand/

        public ActionResult Index()
        {
            return View();
        }

    }
}

SecondHandBusinessPlatform/Controllers/MerchandiseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SecondHandBusinessPlatform.Controllers
{
    public class MerchandiseController : Controller
    {
        //
        // GET: /Merchandise/

        public ActionResult Index()
        {
            return View();
        }

    }
}

SecondHandBusinessPlatform/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="zh-CN">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta charset="utf-8" />
        <title>小型二手货交易平台 - @ViewBag.Title</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        @Styles.Render("~/Content/css")
        @Styles.Render("~/Content/themes/bootstrap")
        @Styles.Render("~/Content/themes/adminlte")
        @Styles.Render("~/Content/themes/font-awesome")
        @Scripts.Render("~/bundles/modernizr")
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @Scripts.Render("~/bundles/application")
    </head>
    <body>
        @Html.Partial("_TopNavBar")
        @RenderSection("featured", required: false)
        @RenderBody()
        @RenderSection("scripts", required: false)
    </body>
</html>

SecondHandBusinessPlatform/Views/Shared/_TopNavBar.cshtml
<nav class="navbar navbar-default" role="navigation">
   <div class="navbar-header">
        <a class="navbar-brand" href="/">SHBP</a>
   </div>
   <div>
      <ul class="nav navbar-nav">
         <li>
            @Html.ActionLink("需求市场", "Index", "Demand")
         </li>
         <li>
            @Html.ActionLink("商品市场", "Index", "Merchandise")
         </li>
       </ul>
       <ul class="nav navbar-nav navbar-right">
         <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
               用户管理
            </a>
            <ul class="dropdown-menu">
                @if (Session["UserId"] != null)
                {
                    <li>
                        @Html.ActionLink("个人信息", "Details", "User")
                    </li>
                    <li>
                        @Html.ActionLink("我的需求", "Demand", "User")
                    </li>
                    <li>
                        @Html.ActionLink("我的商品", "Merchandise", "User")
                    </li>
                    <li>
                        @Html.ActionLink("我的交易", "Transaction", "User")
                    </li>
                    <li class="divider"></li>
                    <li>
                        @Html.ActionLink("登出", "LogOut", "User")
                    </li>
                }
                else
                {
                    <li>
                        @Html.ActionLink("登陆", "Login", "User")
                    </li>
                    <li>
                        @Html.ActionLink("注册", "Register", "User")
                    </li>
                }
            </ul>
         </li>
      </ul>
   </div>
</nav>